import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Project Leader & Full Stack Mobile Developer",
    company: "Bit House",
    logo: "/images/careers/bithouse.jpg",
    location: "Bali, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Project Based",
    start_date: "2025-03",
    end_date: "2025-06",
    industry: "Technology",
    link: "https://bithouse.id/",
    responsibilities: [
      "Led a cross-functional team in collaboration with Bithouse to solve real-world problems through IoT and mobile technology.",
      "Developed a native Android application using Kotlin for real-time interaction with IoT hardware.",
      "Built and maintained backend services using Express.js and integrated with Firebase Realtime Database.",
      "Deployed RESTful APIs on Google Cloud Platform (GCP) for scalable and secure mobile access.",
      "Coordinated with team members responsible for hardware assembly, ESP32 programming, and sensor integration.",
    ],
  },
  {
    position: "Junior Genesys Cloud Administrator",
    company: "PT. Solusi Tiga Selaras",
    logo: "/images/careers/Solutif.jpeg",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Internship",
    start_date: "2024-09",
    end_date: "2024-12",
    industry: "Technology",
    link: "https://www.solutif.co.id/",
    responsibilities: [
      "Implemented Genesys Cloud features (call routing, user management, monitoring) to streamline operations.",
      "Configured BYOC for telephony integration, supporting flexible communication setups.",
      "Optimized workflows to improve call flow efficiency and simulate real-world contact center scenarios.",
      "Reduced routing response time by 60% (from 5s to 2s) through DID and queue configuration, ensuring high system availability.",
    ],
  },
  {
    position: "Human Capital Management",
    company: "PT. Niramas Utama",
    logo: "/images/careers/niramas.jpg",
    location: "Bekasi, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2020-07",
    end_date: "2021-01",
    industry: "Food & Beverage",
    link: "https://www.inacofood.com/",
    responsibilities: [
      "Managed employee data entry into the HRIS, including leave records, sick days, permissions, and contract updates, ensuring data accuracy and consistency.",
      "Assisted in the contract signing process and maintained internal employee correspondence to support HR operations.",
      "Collaborated with the Human Capital team to manage employee relations and administrative processes.",
      "Handled data entry of over 150 employee records into the HRIS, ensuring error-free and well-organized administrative processes.",
    ],
  },
];
